name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ 7.4 ]
        composer: [ 2 ]
        drupal: [ ^8.8, ^9 ]
        include:
          - php: 7.4
            composer: 1
            drupal: 8.8.9
          - php: 7.4
            composer: 1
            drupal: ~8.8.9
          - php: 8.0
            drupal: ^9

    services:
      database:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: test

    env:
      SIMPLETEST_BASE_URL: http://localhost:8888
      SIMPLETEST_DB: mysql://root@127.0.0.1:3306/test
      BROWSERTEST_OUTPUT_DIRECTORY: ${{ github.workspace }}/web/sites/simpletest/browser_output

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:${{ matrix.composer }}

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir --global)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ github.run_number }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup Drupal
        run: |
          composer create-project drupal/recommended-project:${{ matrix.drupal }} . --no-progress
          composer require --dev drupal/core-dev:${{ matrix.drupal }} phpstan/phpstan phpstan/phpstan-deprecation-rules phpstan/phpstan-phpunit mglaman/phpstan-drupal --update-with-all-dependencies --no-progress
          mkdir -p web/sites/simpletest/browser_output
          chmod -R 777 web/sites/simpletest

      - name: Add phpspec/prophecy-phpunit
        if: ${{ matrix.drupal == '^9' }}
        run: composer require --dev phpspec/prophecy-phpunit:^2

      - uses: actions/checkout@v2
        with:
          path: module

      - name: Setup config
        run: |
          ln -s module/phpcs.xml.dist .
          ln -s module/phpstan.neon.dist .
          cp module/phpunit.xml.dist .

      - name: Install module
        run: |
          composer config repositories.local path $GITHUB_WORKSPACE/module
          composer require el7cosmos/social_auth_discourse:dev-main --no-progress

      - name: PHP_CodeSniffer
        run: vendor/bin/phpcs

      - name: PHPStan
        run: vendor/bin/phpstan analyse --no-progress module/src module/tests

      - name: Start php built-in server
        run: php -S localhost:8888 .ht.router.php &
        working-directory: web

      - name: Run test suite
        if: ${{ matrix.drupal == '^9' }}
        run: vendor/bin/phpunit --group=social_auth --coverage-clover=$GITHUB_WORKSPACE/module/coverage.xml --coverage-filter=web/modules/custom/social_auth_discourse/src
        env:
          SYMFONY_DEPRECATIONS_HELPER: disabled
      - name: Run test suite
        if: ${{ matrix.drupal != '^9' }}
        run: vendor/bin/phpunit --group=social_auth --coverage-clover=$GITHUB_WORKSPACE/module/coverage.xml --whitelist=web/modules/custom/social_auth_discourse/src

      - name: Archive test output
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          path: web/sites/simpletest/browser_output

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          working-directory: ${{ github.workspace }}/module
