name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [7.4]
        drupal-versions: [8.8.9, ~8.8.12, ^8.8, ^9]
        include:
          - php-versions: 8.0
            drupal-versions: ^9

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}

      - name: Validate composer.json
        run: composer validate --strict

      - name: Get composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --prefer-dist --ansi

      - run: composer update --with drupal/core:${{ matrix.drupal-versions }} --with drupal/core-dev:${{ matrix.drupal-versions }} -W --ansi

      - run: vendor/bin/phpcs --colors
      - run: vendor/bin/phpstan --no-progress --ansi

      - name: Run test suite
        if: ${{ matrix.drupal-versions == '^9' }}
        run: vendor/bin/phpunit tests --coverage-clover=coverage.xml --coverage-filter=src  --colors=always
      - name: Run test suite
        if: ${{ matrix.drupal-versions != '^9' }}
        run: vendor/bin/phpunit tests --coverage-clover=coverage.xml --whitelist=src --colors=always

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
